modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory
license="MIT"

[[mods]] #mandatory
modId="bonysmod" #mandatory
version="1.0.0" #mandatory
displayName="Bony's Mod" #mandatory
description='''
A mod that adds champion zombies to Minecraft with different levels and abilities.
Champion zombies can climb walls and have special effects depending on their level.
''' #mandatory